CREATE DATABASE HOMEWORK5;
USE HOMEWORK5;
CREATE TABLE movie_information(id int,Actor_id int, movie_name varchar(20),Actor_name varchar(20),Director_name varchar(10));
CREATE TABLE bank_information(id int, no_of_branch int,bank_name varchar(20),bank_branch_name varchar(20),address varchar(20));
ALTER table movie_information add column producer_name varchar(20);
ALTER table movie_information add column production_name varchar(20);
ALTER table movie_information add column producer_phone_no bigint;
ALTER table movie_information add column director_phone_no bigint;
ALTER table movie_information add column movie_is_released boolean;
ALTER table bank_information add column account_holder_name varchar(20);
ALTER table bank_information add column account_holder_address varchar(20);
ALTER table bank_information add column account_holder_phone_no bigint;
ALTER table bank_information add column bank_phone_no bigint;
ALTER table bank_information add column bank_is_opened boolean;
SELECT * FROM movie_information;
SELECT * FROM bank_information;
ALTER table movie_information rename column producer_name to p_name;
ALTER table movie_information rename column production_name to pro_name;
ALTER table movie_information rename column producer_phone_no to p_phone_no;
ALTER table movie_information rename column director_phone_no to d_phone_no;
ALTER table movie_information rename column movie_is_released  to m_is_released;
ALTER table bank_information rename column account_holder_name to a_holder_name;
ALTER table bank_information rename column account_holder_address to a_holder_address;
ALTER table bank_information rename column account_holder_phone_no to a_holder_phone_no;
ALTER table bank_information rename column bank_phone_no to b_phone_no;
ALTER table bank_information rename column bank_is_opened to b_is_opened;
INSERT INTO movie_information values(1,1,'kgf1','yash1','suri1','abc1','hombale1',1234567890,0987654321,true);
INSERT INTO movie_information values(2,2,'kgf2','yash2','suri2','abc2','hombale2',1234567891,0987654311,false);
INSERT INTO movie_information values(3,3,'kgf3','yash3','suri3','abc3','hombale3',1234567892,0987654322,true);
INSERT INTO movie_information values(4,4,'kgf4','yash4','suri4','abc4','hombale4',1234567893,0987654323,true);
INSERT INTO movie_information values(5,5,'kgf5','yash5','suri5','abc5','hombale5',1234567894,0987654324,false);
INSERT INTO movie_information values(6,6,'kgf6','yash6','suri6','abc6','hombale6',1234567895,0987654325,true);
INSERT INTO movie_information values(7,7,'kgf7','yash7','suri7','abc7','hombale7',1234567896,0987654326,false);
INSERT INTO movie_information values(8,8,'kgf8','yash8','suri8','abc8','hombale8',1234567897,0987654327,true);
INSERT INTO movie_information values(9,9,'kgf9','yash9','suri9','abc9','hombale9',1234567898,0987654328,false);
INSERT INTO movie_information values(10,10,'kgf10','yash10','suri10','abc10','hombale10',1234567899,0987654329,true);
INSERT INTO bank_information values(1,1,'canarabank','canara','shivamogga','ananya','shivamogga',9019520593,1234567890,true);
INSERT INTO bank_information values(2,2,'canarabank1','canara1','shivamogga1','ananya1','Mysore',9019520594,1234567891,false);
INSERT INTO bank_information values(3,3,'canarabank2','canara2','shivamogga2','ananya2','sagar',9019520595,1234567892,true);
INSERT INTO bank_information values(4,4,'canarabank3','canara3','shivamogga3','ananya3','davangere',9019520596,1234567893,false);
INSERT INTO bank_information values(5,5,'canarabank4','canara4','shivamogga4','ananya4','hasan',9019520597,1234567894,true);
INSERT INTO bank_information values(6,6,'canarabank5','canara5','shivamogga5','ananya5','shivamogga',9019520598,1234567890,false);
INSERT INTO bank_information values(7,7,'canarabank6','canara6','shivamogga6','ananya6','gadag',9019520599,1234567880,true);
INSERT INTO bank_information values(8,8,'canarabank7','canara7','shivamogga7','ananya7','hubli',9019520591,1234567870,true);
INSERT INTO bank_information values(9,9,'canarabank8','canara8','shivamogga8','ananya8','dharwad',9019520592,1234562890,false);
INSERT INTO bank_information values(10,10,'canarabank9','canara9','shivamogga9','ananya9','shivamogga',9019520590,1634567890,true);

UPDATE bank_information set address='bengaluru' where id=2;
UPDATE bank_information set address='mysore' where id=3;
UPDATE bank_information set address='mandya' where id=4;
UPDATE bank_information set address='hubli' where id=5;
UPDATE bank_information set address='dharwad' where id=6;
UPDATE bank_information set address='belgam' where id=7;
UPDATE bank_information set address='sagara' where id=8;
UPDATE bank_information set address='gadag' where id=9;
UPDATE bank_information set address='kodagu' where id=10;
UPDATE bank_information set address='changiri' where id=1;

UPDATE movie_information set Actor_name='Ananya' where id=2;
UPDATE movie_information set Actor_name='Sudeep' where id=3;
UPDATE movie_information set Actor_name='Darshan' where id=4;
UPDATE movie_information set Actor_name='Prem' where id=5;
UPDATE movie_information set Actor_name='Prathap' where id=6;
UPDATE movie_information set Actor_name='Pradeep' where id=7;
UPDATE movie_information set Actor_name='sagar' where id=8;
UPDATE movie_information set Actor_name='gagan' where id=9;
UPDATE movie_information set Actor_name='chiru' where id=10;
UPDATE movie_information set Actor_name='sunil' where id=1;

DELETE FROM movie_information where id=7;
DELETE FROM movie_information where id=3;
DELETE FROM movie_information where id=5;

DELETE FROM bank_information where id=1;
DELETE FROM bank_information where id=2;
DELETE FROM bank_information where id=4;

UPDATE  bank_information SET b_is_opened=false where id in (3,5,7);
rollback;
SELECT * FROM bank_information where id in (6,8);
SELECT * FROM bank_information where id not  in (9,10);
SELECT * FROM bank_information where id =8 and address='sagar';
SELECT * FROM bank_information where id =8 or address='sag';

UPDATE  movie_information SET m_is_released=true where id in (2,9);
rollback;
SELECT * FROM movie_information where id in (1,2);
SELECT * FROM movie_information where id not  in (3,14);
SELECT * FROM movie_information where id =8 and Actor_name='Prathap';
SELECT * FROM movie_information where id =8 or Actor_name='Prathap';
